<a href="https://colab.research.google.com/github/Jahan08/Ambertools-CP2K-MM-QM-Biomolecular-Simulation/blob/main/Cytotoxicity-data-preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df_url = 'https://github.com/Jahan08/Ambertools-CP2K-MM-QM-Biomolecular-Simulation/raw/main/AD3C_Tox_CC50_230502_cellline_1.xlsx'
df = pd.read_excel(df_url)
df

,OBJID_BATCH,LIBRARY,SUPPLIER_ID,TESTSET,CC50_UM,DR_STATUS,CELLLINE,Smiles
0,AB00282301_01,CB2,Chembridge 2_5944619,20141226_FluLucToxDR,>67.78,Inactive,HEK293,n(c1c(s2)cccc1)(c(SC)nn3)c23
1,AB00282251_01,CB2,Chembridge 2_5940003,20141226_FluLucToxDR,>63.74,Inactive,HEK293,n(c1c(s2)cccc1)(c(SCC)nn3)c23
2,AB00291997_01,CB2,Chembridge 2_6641075,20141226_FluLucToxDR,>47.56,Inactive,HEK293,n1(c2c(s3)cccc2)c3nnc1SCc4ccccc4F
3,AB00315535_01,CB2,Chembridge 2_7355340,20141226_FluLucToxDR,>43.173,Inactive,HEK293,n1(c2c(s3)cccc2)c3nnc1SCC(=O)Nc4sccn4
4,AB00310192_01,CB2,Chembridge 2_7228337,20141226_FluLucToxDR,>39.423,Inactive,HEK293,n1(c2c(s3)cccc2)c3nnc1SCC(=O)N4c5c(CC4C)cccc5
...,...,...,...,...,...,...,...,...
18029,AB01973690_01,AD3C_S107,SRI Repository_SRI-00047488,NaN,NaN,NaN,NaN,O=C(c1c([nH]nn1)Nc2ccc3c(NC(=O)CO3)c2)Nc4c(ccc...
18030,AB01973691_01,AD3C_S107,SRI Repository_SRI-00047489,NaN,NaN,NaN,NaN,c1c(Nc2nc(c3ccc(c4)c(ccc4)c3)cs2)n(c5ccccc5)nc...
18031,AB01973692_01,AD3C_S107,SRI Repository_SRI-00047490,NaN,NaN,NaN,NaN,c1(Nc2cc(Cl)ccc2)snnc1C(Nc3c(C)cccc3C)=O
18032,AB01973693_01,AD3C_S107,SRI Repository_SRI-00047491,NaN,NaN,NaN,NaN,O=C(c1c([nH]nn1)Nc2ccc(Cl)nc2)Nc3c(C)cccc3C
18033,AB01973694_01,AD3C_S107,SRI Repository_SRI-00047432,NaN,NaN,NaN,NaN,C1(=O)c2c(n(CCOc3ccccc3)c(cc4OCCOc5ccccc5)c2cc...